### ISSUE TITLE
Prepare releases and packaging

### ISSUE THREAD

**Issue by Lucki** [lhark/truckersmp-cli#58]
To bring this project further we can start tagging releases which also potentially will make it packable for distributions. With #57 we have a solid base for future changes we can build upon.

- Script adjustments
  - [x] Care about repo installations (#77)
  - [x] We should re-evaluate our self-update part since it will probably much more frequent be a plain download or repo installation instead of a git checkout. We should also consider a way to disable this check, maybe on path detection? (#82)
  - [x] Automate update branch detection (#63)
  - [x] Sane defaults for everything (#69)
    - Proton as default
    - Start as default
    - Update as default?
    - ETS2 as default
  - [x] Automatic current steam user detection. (#67)
  - [x] Remove waiting on user input in `start_with_wine()` (#83)
  - [x] I probably missed something…

- Github adjustments
  - [x] We should create a new GitHub action which will create a changelog since the last release and bundle everything up in case someone finds the release section. (#64)
  - [x] Start tagging releases (#78)
  - [x] Remove the binary from the repo and include it in the release tarball (#78)
  - [x] Update README (#80)
    - Dependencies > Optional (Add (python3-)pip and vdf)
    - Install (Replace current content with new installation instruction after publishing)
    - Overhaul everything as it's quite messy
    - Add us to it
  - [x] Investigate automatic bash/zsh autocompletion generation (#70, #75)
  - [x] provide installation through `setup.py` (#77)
  - [x] try to package for PyPi (#81)
  - [x] Care about PyPi installations (#80, #81)
  - [x] Provide an Issue template (#74)
    - Code blocks and spoiler for logs
  - [x] I probably missed something…

**Comment by kakurasan** [comment]
> Evaluate providing a file similar to proton.json for the current used ets2 and ats versions.

The easiest way is to get the information from stats.truckersmp.com:

```python
#!/usr/bin/env python3

"""
Print supported ETS2/ATS version information.

This script gets information from https://stats.truckersmp.com/
"""

import html.parser
import urllib.request


class URL:
    """URLs."""

    stats = "https://stats.truckersmp.com"


def get_supported_game_versions():
    """Get supported ETS2/ATS version information."""
    html = ""
    with urllib.request.urlopen(URL.stats) as f:
        html += f.read().decode("utf-8")

    parser = StatsHTMLParser()
    parser.feed(html)
    return parser.data


class StatsHTMLParser(html.parser.HTMLParser):
    """HTML parser for stats.truckersmp.com."""

    _data = {}
    _name = None
    _supported_elem = False

    def handle_starttag(self, tag, attrs):
        """HTML start tag handler."""
        for attr in attrs:
            if (attr[0] == "id"
                    and len(attr) == 2
                    and attr[1].endswith("supported_version")):
                self._name = attr[1][:attr[1].index("_")]

    def handle_endtag(self, tag):
        """HTML end tag handler."""
        self._name = None

    def handle_data(self, data):
        """HTML data handler."""
        if self._name:
            self._data[self._name] = data

    @property
    def data(self):
        """Return supported version information."""
        return self._data


if __name__ == "__main__":
    print(get_supported_game_versions())
```

```
$ ./print_supported_version.py
{'ets2': '1.36.2.55s', 'ats': '1.36.1.40s'}
```

Another way is to find the string "Expected:" from `core_*mp.dll`:

```
$ upx -d core_ets2mp.dll
$ strings core_ets2mp.dll | grep "Expected:"
Expected: ver. 1.36.2.55s [rev. e0862fcae485]
$ upx -d core_atsmp.dll
$ strings core_atsmp.dll | grep "Expected:"
Expected: ver. 1.36.1.40s [rev. 8de099f4740c]
```

In any case, I think *we don't need to provide or maintain the information*.

**Comment by Lucki** [comment]
Great find! Independent of the way we're choosing to get that information I don't think we can always update to the `temporary_1_36` branch. Any idea how we can decide automatically if we need to update to the temporary or the public branch?

> Re-evaluate if we need to close steam for updating. The related issue was closed some time ago.

I just tried again and while steam still looses connection ~~it hasn't asked me again to log in and provide a guard code.~~and asks me to log in again. But the 0 kb downloads of all proton games aren't there anymore. Maybe we can somehow avoid loosing connection in the first place.

> Try to get the current steam user automatic

We can get the latest user from `loginusers.vdf` and see if they're authenticated.

> try to hook into the current/latest session.

It seems possible to run some commands in the steam console but "force_install_dir" isn't recognized.

**Comment by kakurasan** [comment]
> Any idea how we can decide automatically if we need to update to the temporary or the public branch?

It's difficult to decide *automatically*, but we might be able to avoid upgrading to TruckersMP-incompatible version by checking whether "It's time to downgrade!" announcement is present. As of May 3 2020, truckersmp.com says that "TruckersMP doesn't support the latest game version of American Truck Simulator yet."

> We can get the latest user from `loginusers.vdf` and see if they're authenticated.

We use this file for detecting Steam installation directory and we don't know the path to `[Steam installation directory]/config/loginusers.vdf` before logging in.
We can use our own configuration file to allow users to omit `-n` (`--account`) option.

> Set up proton as default?

I think it's fine, but I don't want to drop Wine support.

> Maybe default to ETS2?

Fine, I think. Number of ETS2MP players is greater than ATSMP.

**Comment by Lucki** [comment]
> get the information from stats.truckersmp.com:

> "It's time to downgrade!" announcement

There's even an [API](https://stats.truckersmp.com/api#version), https://api.truckersmp.com/v2/version
<details><summary>The games version is included in the executable we can compare them and decide if a downgrade is needed.</summary>

![grafik](https://user-images.githubusercontent.com/1408843/80916178-6981b200-8d57-11ea-806a-7fb261463ae5.png)
</details>
I think that's more elegant than scraping the website.

> I don't want to drop Wine support.

Me neither. I think we should provide sane defaults to everything possible so when someone doesn't know what he's doing and just runs the script the script does something and it "just works".

> we don't know the path to `[Steam installation directory]/config/loginusers.vdf` before logging in.

The file's already present before logging in if steam was started at least once. We can test the known paths and read the file if it's found.

When the file isn't found we can abort and ask to provide the login credentials.

**Comment by kakurasan** [comment]
When I start ETS2, "1.36.2.55s (64-bit)" is displayed, but the information in PE file is currently different from this. Check your screenshot carefully, it's not "1.36.2.*55*" but "1.36.2.*48*".

I tested with Python + [pefile](https://github.com/erocarrera/pefile) and I got the same result:

```
>>> import pefile
>>> ets2 = pefile.PE("/path/to/eurotrucks2.exe", fast_load=False)
>>> ets2.FileInfo[0][0].StringTable[0].entries
{b'CompanyName': b'SCS Software', b'FileDescription': b'Euro Truck Simulator 2 - Steam', b'FileVersion': b'1.36.2.48 (e0862fcae48536b292a0960b776022fd68854e62)', b'InternalName': b'eurotrucks', b'LegalCopyright': b'Copyright (C) SCS Software 2013', b'LegalTrademarks': b'Euro Truck Simulator 2 (C) SCS Software 2013', b'OriginalFilename': b'eurotrucks2.exe', b'ProductName': b'Euro Truck Simulator 2', b'ProductVersion': b'1.36.2.48'}
```

Can we trust this information?

**Comment by Lucki** [comment]
Hm, fair question. I've checked for ATS and it tells me `VALUE "ProductVersion",    "1.37.1"` so my guess is it's somewhat recent. Since we could downgrade only to `1.36` we don't have to care about the minor versions anyway? Blocking an update is more difficult however. Maybe scraping the website for this purpose is indeed better.

**Comment by Lucki** [comment]
Looks like we've addressed all things we've came up with.
I don't know why but I somehow feel we should get rid of the short `-c` option.

Anything other missing? Maybe wanna chat (steam, irc, discord, …)?

**Comment by kakurasan** [comment]
I think we're already ready to release version 0.1.0.

> I don't know why but I somehow feel we should get rid of the short `-c` option.

I guess many users want to use DXVK (d3d11) and it's *easier to specify*.

I also feel something strange, but I don't feel like changing it without a solid reason.

> Anything other missing? Maybe wanna chat (steam, irc, discord, …)?

1. Do we add a short option for `--beta` (e.g. `-b`)?
2. What about the `desc` in `create_arg_parser()`?

As you already know, I'm not good at communicating in English.
Especially I cannot reply quickly...

**Comment by Lucki** [comment]
No problem, would be fine ;)

What bothers me about `-c` is that's only a one-time command. And the actual DX11 argument only exists in a long version. I'll propose to remove `-c` and add `-d` for `--enable-d3d11`.

> 1. Do we add a short option for `--beta` (e.g. `-b`)?

`-b` is also a good addition.

>  2\. What about the `desc` in `create_arg_parser()`?

That's what I meant with syncing the help texts.

**Comment by Lucki** [comment]
Whoops, I seem to have accidentally already checked the box for waiting on user input in `start_with_wine()` which isn't resolved yet. Discussion was in #63
